name: Build and deploy Node.js app to Azure Web App - ecoomerce3dvision

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm install
          npm audit fix --force
          npm run build --if-present
          npm run test --if-present -- --passWithNoTests

      - name: Zip artifact for deployment
        run: zip -r release.zip ./build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3 # Actualizado a v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3 # Actualizado a v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB4DF85B12744EC2A954EAA7B1FA3034 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A8C578F6B7124D3D8918A525B1076459 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA8D2368557C4A73B05962E209895DE1 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecoomerce3dvision'
          slot-name: 'Production'
          package: .
